general {
    lock_cmd = pidof drift || drift
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 10
    on-timeout = kitty --class drift -e drift --scene clock --theme dracula
    on-resume = pkill -f "kitty --class drift"
}
